prepare:
  dateInit: 20050101 
  dateEnd: 20161231
  shift: 0
  station: station1
  nTest: 0.01
  stepsIn: 12
  stepsOut: 12
  nFeatures: 2
train:
  activation1: 'tanh'
  activation2: 'tanh'
  optimizer: 'adam'
  nFeatures: 2
  validation: 0.1
  loss: 'mse'
  epochs: 20
  verbose: 2
  batch: 32
evaluate:
  lat: -85
  long: -120
evaluate_specific_date_range:
  dateInit: 20161118
  dateEnd: 20161231
  amountOfDays: 43
  dateInitNaiveAvg: 20161023
  isTestSet: True
  pathSymH: "/home/jorge/Downloads/final_symh_2017_to_2018.csv"
  #plotTitle1: "Frozen ionosphere method versus actual data on the test set (Nov-Dec 2016)"
  #plotTitle2: "27-days-avg naive method versus actual data on the test set (Nov-Dec 2016)"
  #plotTitleForTestSet: "CNN method versus actual data on the test set (Nov-Dec 2016)"